export const GET_COMPANY = 'GET_COMPANY';
export const GET_COMPANY_SUCCESS = 'GET_COMPANY_SUCCESS';
export const GET_COMPANY_FAILED = 'GET_COMPANY_FAILED';

export const GET_CASHCOUNT = 'GET_CASHCOUNT';
export const GET_CASHCOUNT_SUCCESS = 'GET_CASHCOUNT_SUCCESS';
export const GET_CASHCOUNT_FAILED = 'GET_CASHCOUNT_FAILED';

export const GET_SUM_RING_BY_REGION = 'GET_SUM_RING_BY_REGION';
export const GET_SUM_RING_BY_REGION_SUCCESS = 'GET_SUM_RING_BY_REGION_SUCCESS';
export const GET_SUM_RING_BY_REGION_FAILED = 'GET_SUM_RING_BY_REGION_FAILED';

export const GET_SUM_RING_BY_PROVIENCE = 'GET_SUM_RING_BY_PROVIENCE';
export const GET_SUM_RING_BY_PROVIENCE_SUCCESS =
  'GET_SUM_RING_BY_PROVIENCE_SUCCESS';
export const GET_SUM_RING_BY_PROVIENCE_FAILED =
  'GET_SUM_RING_BY_PROVIENCE_FAILED';

export const GET_LIST_RING = 'GET_LIST_RING';
export const GET_LIST_RING_SUCCESS = 'GET_LIST_RING_SUCCESS';
export const GET_LIST_RING_FAILED = 'GET_LIST_RING_FAILED';

export const GET_LIST_PAGING_RING = 'GET_LIST_PAGING_RING';
export const GET_LIST_PAGING_RING_SUCCESS = 'GET_LIST_PAGING_RING_SUCCESS';
export const GET_LIST_PAGING_RING_FAILED = 'GET_LIST_PAGING_RING_FAILED';
